export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div style={{minHeight: '100vh', display: 'flex', flexDirection: 'column'}}>
          {children}
        </div>
        <style>{`
          html,body,#__next{height:100%}
          body{margin:0;font-family: system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial}
        `}</style>
      </body>
    </html>
  )
}
